- hosts: web
  tasks:
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest
    - name: Make sure a service is running
      systemd:
        name: httpd 
        state: started
    - name: Enable service httpd and ensure it is not masked
      systemd:
        name: httpd
        enabled: yes
        masked: no
    - name: Download Templates
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page258/bluesky.zip
        dest: /var/www/html/
    - name: Install unzip
      yum:
        name: unzip
        state: latest
    - name: unzip 
      unarchive:
        src: /var/www/html/bluesky.zip
        dest: /var/www/html/
        remote_src: yes
    - name: Move Files
      shell: mv /var/www/html/bluesky/* /var/www/html/